import requests
import os
import sys

if sys.platform == 'win32':
    try: sys.stdout.reconfigure(encoding='utf-8')
    except: pass

from dotenv import load_dotenv
load_dotenv()

SB_URL = "https://khskudtxbypohvnreloi.supabase.co"
SB_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtoc2t1ZHR4Ynlwb2h2bnJlbG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYzMTIwMjksImV4cCI6MjEwMTg4ODAyOX0.jrK8y5zpDncgFkmdD4hkFRd5-kW1gWdVSRIb0jh7o2I"
SB_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtoc2t1ZHR4Ynlwb2h2bnJlbG9pIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjMxMjAyOSwiZXhwIjoyMTAxODg4MDI5fQ.uyCTVGkoeoz4xB3r2muV_fLiI62QIw-65g2nVeIb62w")

USE_KEY = SB_SERVICE_KEY if SB_SERVICE_KEY else SB_ANON_KEY

HEADERS = {
    "apikey": USE_KEY,
    "Authorization": f"Bearer {USE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=representation"
}

print(f"Connecting to Supabase: {SB_URL}")

# Check tables
tables_to_check = ["sniper_filters", "sniper_parsed_trips", "sniper_settings"]
missing = False

for table in tables_to_check:
    r = requests.get(f"{SB_URL}/rest/v1/{table}?limit=1", headers=HEADERS)
    if r.status_code == 200:
        print(f"✅ Table '{table}' exists and is ready.")
    elif r.status_code == 404:
        print(f"❌ Table '{table}' DOES NOT EXIST!")
        missing = True
    else:
        print(f"⚠️ Table '{table}' returned status {r.status_code}: {r.text}")
        missing = True

if missing:
    print("\n" + "=" * 60)
    print("📋 يرجى نسخ الكود التالي وتشغيله في Supabase Dashboard > SQL Editor:")
    print("=" * 60)
    sql = """
-- 1. جدول فلاتر قناص التشغيلات
CREATE TABLE IF NOT EXISTS public.sniper_filters (
    id bigint generated by default as identity primary key,
    origin text not null,
    destination text not null,
    car_type text, -- 'sedan' | 'minivan' | 'van' | null (أي نوع)
    created_at timestamp with time zone default now() not null
);

-- تفعيل RLS لجدول الفلاتر
ALTER TABLE public.sniper_filters ENABLE ROW LEVEL SECURITY;

-- السماح بكل العمليات لجدول الفلاتر
CREATE POLICY "allow_all_sniper_filters" ON public.sniper_filters
    FOR ALL USING (true) WITH CHECK (true);


-- 2. جدول الرحلات الملتقطة والمحللة
CREATE TABLE IF NOT EXISTS public.sniper_parsed_trips (
    id bigint generated by default as identity primary key,
    group_name text,
    sender_name text,
    raw_message text,
    operation_type text, -- 'sale' (بيع) | 'request' (طلب) | 'exchange' (بدل)
    origin text,
    destination text,
    date_time text,
    price numeric,
    car_type text,
    contact_phone text,
    office_name text,
    is_matched boolean default false,
    created_at timestamp with time zone default now() not null
);

-- تفعيل RLS لجدول الرحلات الملتقطة
ALTER TABLE public.sniper_parsed_trips ENABLE ROW LEVEL SECURITY;

-- السماح بكل العمليات لجدول الرحلات الملتقطة
CREATE POLICY "allow_all_sniper_parsed_trips" ON public.sniper_parsed_trips
    FOR ALL USING (true) WITH CHECK (true);


-- 3. جدول إعدادات القناص
CREATE TABLE IF NOT EXISTS public.sniper_settings (
    key text primary key,
    value text,
    created_at timestamp with time zone default now() not null
);

-- تفعيل RLS لجدول الإعدادات
ALTER TABLE public.sniper_settings ENABLE ROW LEVEL SECURITY;

-- السماح بكل العمليات لجدول الإعدادات
CREATE POLICY "allow_all_sniper_settings" ON public.sniper_settings
    FOR ALL USING (true) WITH CHECK (true);

-- إدراج القيم الافتراضية
INSERT INTO public.sniper_settings (key, value)
VALUES 
    ('telegram_token', '7558216970:AAEwKrLQfSCiFgB5o1Ok3TgFvvE_k-jsK_M'),
    ('telegram_chat_id', null)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
"""
    print(sql)
    print("=" * 60)
else:
    print("\n🎉 All sniper database tables are verified and ready!")
